---
apiVersion: v1
kind: Service
metadata:
  name: adminfrontendf
  namespace: micropaas
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      ambassador_id: default
      name:  adminfrontendf_micropaas_mapping
      host:  admin.micropaas.ies.f
      prefix:  /
      service: adminfrontendf.micropaas:80
      timeout_ms: 900000
spec:
  ports:
    - name: http-admin-fontend-f
      port: 80
      targetPort: adminfrontendf
  selector:
    app: adminfrontendf

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adminfrontendf
  namespace: micropaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminfrontendf
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: adminfrontendf
    spec:
      imagePullSecrets:
        - name: regcred-atcdevops
      containers:
        - name: adminfrontend
          image: harbor.atcdevops.accenture.cn/micropaas/admin_frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: adminfrontendf

